default: &default
  adapter: mysql2
  username: root
  password: dummy
  host: <%= ENV['DB_MYSQL_HOST'] || '127.0.0.1' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: pokemon_development

test:
  <<: *default
  database: pokemon_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: pokemon_prodcution
  username: pokemon
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
