name: Continuous integration

env:
  RUBY_VERSION: 2.6.6
  BUNDLER_VERSION: 2.2.0
  RAILS_ENV: test
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: dummy
  MYSQL_ROOT_PASSWORD: dummy
  MYSQL_HOST: 127.0.0.1
  MYSQL_PORT: 3306
  MYSQL_DATABASE: pokemon_test

on: push
jobs:
  test:
    name: "RSpec Tests"
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: dummy
          MYSQL_ROOT_PASSWORD: dummy
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: pokemon_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install default-libmysqlclient-dev default-mysql-client
      - name: Restore bundle cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle
        env:
          RAILS_ENV: test
        run: |
          gem install bundler:${{ env.BUNDLER_VERSION }}
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Setup Database
        run: |
          bundle exec rake db:test:prepare
      - name: Run tests
        run: |
          bundle exec rspec
